#net_setup.conf (read by net_setup.pl)
NAME=FOR_USE_IN_LOGS

LAN_IF=wlp3s0
WAN_IF=enp1s0

LAN_NET=192.168.50.0/24
LAN_IP=192.168.50.1

WAN_NET=10.10.10.0/24
WAN_GW=10.10.10.1

ALLOW_SSH=1
SSH_PORT=22

ALLOW_DHCP=1
ALLOW_DNS=0

ENABLE_NAT=1
ENABLE_FORWARD_LAN_TO_WAN=1

LOG_DROPS=1

EXTRA_FORWARD_SRC=10.10.10.0/24
EXTRA_FORWARD_IF=labbr0

#Port forwarding setup (for external honeypot or similar)
#PORT_FORWARD1=<incoming_if>:<public_port>,<outgoing_if>,<target_ip>:<target_port>
PORT_FORWARD1=enp1s0:2222,enp1s0,10.10.10.11:2222
PORT_FORWARD2=enp1s0:2223,wlx088af12de289,192.168.50.11:2222

OPEN_INCOMING_PORT1=enp1s0,udp,514
OPEN_INCOMING_PORT2=enp1s0,udp,5551,5552
#OPEN_INCOMING_PORT3=enp1s0,tcp,2222
#OPEN_INCOMING_PORT4=enp1s0,tcp,8000-8005

DROP_LOG=1
DROP_LOG_PROTOCOL=[syslog|UDP514|rsyslog^10.10.10.10]

