#net_setup.conf (read by net_setup.pl)
NAME=FOR_USE_IN_LOGS

LAN_IF=wlx088af12de289
WAN_IF=enp1s0

LAN_NET=192.168.50.0/24
LAN_IP=192.168.50.1

WAN_NET=10.10.10.0/24
WAN_GW=10.10.10.254

ALLOW_SSH=1
SSH_PORT=22

ALLOW_DHCP=1
ALLOW_DNS=0

ENABLE_NAT=1
ENABLE_FORWARD_LAN_TO_WAN=1

LOG_DROPS=1

EXTRA_FORWARD_SRC=10.10.10.0/24
EXTRA_FORWARD_IF=labbr0

DROP_LOG=1
DROP_LOG_PROTOCOL=[syslog|UDP514|rsyslog^10.10.10.10]

